version: '3'
services:
  wiki:
    image: dunglas/frankenphp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - "443:443"
      - "2019:2019"
      - '${VITE_PORT}:${VITE_PORT}'
    environment:
      WWWUSER: '${WWWUSER}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      PHP_IDE_CONFIG: serverName=orca-test
      CADDY_GLOBAL_OPTIONS: "debug"
      SERVER_NAME: '192.168.178.110, localhost, orca-test'
    volumes:
      - '.:/app'
      # - './Caddyfile:/etc/caddy/Caddyfile'  # Mount the Caddyfile
    networks:
      - wiki_network
    depends_on:
      - mysql
      - redis
      - meilisearch

  mysql:
    image: 'mysql/mysql-server:8.0'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'wiki-mysql:/var/lib/mysql'
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - wiki_network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    expose:
      - '6379'
    volumes:
      - 'wiki-redis:/data'
    networks:
      - wiki_network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    expose:
      - '7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS}'
    volumes:
      - 'wiki-meilisearch:/meili_data'
    networks:
      - wiki_network
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://127.0.0.1:7700/health'
      retries: 3
      timeout: 5s

networks:
  wiki_network:
    driver: bridge

volumes:
  wiki-meilisearch:
    driver: local
  wiki-redis:
    driver: local
  wiki-mysql:
    driver: local
